Repository ArthurDiogenes/gig-front, pull requests merged in 2025-04, with the labels that each got.

#19 Perfil estabelecimento
  public/images/capa.png
  public/images/hard-rock.png
  src/pages/BandProfile/BandProfile.module.css
  src/pages/BandProfile/BandProfile.tsx
  src/pages/PerfilEstabelecimento/PerfilEstabelecimento.module.css
  src/pages/PerfilEstabelecimento/PerfilEstabelecimento.tsx
  src/routes/AppRoutes.tsx
  src/utils/icons.tsx
Labels: sprint-03

#26 feat: Completa o layout da pagina de perfil do estabelecimento
  src/pages/PerfilEstabelecimento/PerfilEstabelecimento.module.css
  src/pages/PerfilEstabelecimento/PerfilEstabelecimento.tsx
  src/utils/icons.tsx
Labels: sprint-04

#28 feat: enviando dados de cidade e endereço do estabelecimento para o back
  src/pages/TelaCadastroEstabelecimento/TelaCadastroEstabelecimento.tsx
Labels: sprint-05
